#!/bin/bash
# Quick fix for CORS issue

echo "=========================================="
echo "  XENOHURU - CORS QUICK FIX"
echo "=========================================="
echo ""
echo "Your Django API needs CORS headers enabled."
echo ""
echo "Run these commands in your Django project:"
echo ""
echo "1. Install django-cors-headers:"
echo "   pip install django-cors-headers"
echo ""
echo "2. Add to settings.py INSTALLED_APPS:"
echo "   'corsheaders',"
echo ""
echo "3. Add to settings.py MIDDLEWARE (at top):"
echo "   'corsheaders.middleware.CorsMiddleware',"
echo ""
echo "4. Add to settings.py:"
echo "   CORS_ALLOW_ALL_ORIGINS = True  # For dev only"
echo ""
echo "5. Restart Django:"
echo "   python manage.py runserver"
echo ""
echo "=========================================="
echo "After fixing, refresh http://localhost:3000"
echo "=========================================="
